# Generated by Django 4.2 on 2023-10-27 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhookevents',
            name='event',
            field=models.CharField(choices=[('user.create', 'user.create'), ('user.update', 'user.update'), ('user.delete', 'user.delete'), ('test.hook', 'test.hook')], max_length=200),
        ),
    ]
