version: '3.8'

services:
  web:
    build: .
    image: sample_project
    # command: python manage.py runserver 0.0.0.0:8000
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: sample_project
    env_file: .env
    volumes:
      - .:/application
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    restart: always
    image: postgres:latest
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      PGPORT: ${DB_PORT}
      HOST: ${DB_HOST}
    ports:
      - ${DB_PORT}:${DB_PORT}

  redis:
    restart: always
    image: redis:latest
    expose:
        - 6379

  celery-worker:
    build: .
    image: sample_project
    command: bash -c "celery -A sample_project worker -l INFO"
    container_name: sample_project_celery_worker
    env_file: .env
    volumes:
      - .:/application
    depends_on:
      - redis
      - db


volumes:
  pgdata: